on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: calcit-lang/setup-cr@0.0.9

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev

      - run: cargo build --release

      - run: mkdir -p dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: xvfb-run cr compact.cirru
